### ISSUE TITLE
Roadmap to QGIS core integration

### ISSUE THREAD

**Issue by ponceta** [opengisch/qgis-document-management-system-plugin#27]
I would be interested in sharing how we could influence and push toward a QGIS core integration of such a functionnality in the future (1-5 years).

As a reminder, what we achieved so far :

1. Polymorphic relation integration in QGIS core
2. QGIS plugin DMS
3. Implementation of the plugin / document management in GIS applications (TEKSI Modules QWAT /QGEP, others ... )

What we will need in the future :

- [ ] End users feedbacks
- [ ] Data managers feedbacks
- [ ] Plugin improvements
- [ ] Solve missing use-cases?
- [ ] QEP at some point ?
